POST https://node-0-crof.onrender.com/videos
Content-Type: application/json

{
  "title": "01 Video",
  "description": "01 Description",
  "duration": 180,
  "channel": "Joel Fernandes"
}

###
GET https://node-0-crof.onrender.com/videos

###
PUT https://node-0-crof.onrender.com/videos/980dd937-264c-4c7b-a6e4-4f3fae1da0c1
Content-Type: application/json

{
  "title": "Video Update 01",
  "description": "Description Update 01",
  "duration": "205",
  "channel": "Simão"
}

###
DELETE https://node-0-crof.onrender.com/videos/980dd937-264c-4c7b-a6e4-4f3fae1da0c1