###
POST https://node-0-crof.onrender.com/videos
Content-Type: application/json

{
  "title": "01 Video",
  "description": "Description 01",
  "duration": 180,
  "channel": "Joel"
}

###
GET https://node-0-crof.onrender.com/videos

###

###
PUT https://node-0-crof.onrender.com/videos/bfbb45bb-c1d9-4b62-bd40-f48d70dd2060
Content-Type: application/json

{
  "title": "02 Video Node",
  "description": "Description 02 Node",
  "duration": 200,
  "channel": "Rocketseat"
}

###

###
DELETE https://node-0-crof.onrender.com/videos/bfbb45bb-c1d9-4b62-bd40-f48d70dd2060
